[package]
name = "fleet-flow"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
directories = { workspace = true }
fs2 = { workspace = true }

# Workspace toolkits
fleet-domain = { workspace = true }
fleet-download = { workspace = true }
fleet-local-state = { workspace = true }
fleet-local-state-inventory = { workspace = true }
fleet-manifest = { workspace = true }
fleet-reconcile = { workspace = true }
swifty-repo = { workspace = true }
flux-manifest = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
axum = { workspace = true }
