[package]
name = "fleet-flux"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
fleet-download = { workspace = true }
flux = { workspace = true }
futures-util = { workspace = true }
object_store = { workspace = true }
swifty-repo = { workspace = true }
swifty_artifacts = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
