[package]
name = "local_index"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1"
manifest_types = { path = "../manifest_types" }
relative-path = "1.9"
rusqlite = { version = "0.30", features = ["bundled"] }
tokio-rusqlite = "0.5"
thiserror = "2"
tokio = { version = "1.43", features = ["rt", "sync"] }
