[package]
name = "fleet_remote_http"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
fleet_types = { workspace = true }
reqwest = { workspace = true, features = ["stream", "rustls-tls"] }
fleet_sync = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[dev-dependencies]
serde_json = "1"
wiremock = "0.6"
