[package]
name = "fleet_scan"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
camino = "1"
manifest_types = { path = "../manifest_types" }
relative-path = "1.9"
md5 = "0.7"
thiserror = "1"
walkdir = "2"

[dev-dependencies]
camino = "1"
manifest_types = { path = "../manifest_types" }
