[package]
name = "fleet-ui"
version = "0.2.0"
edition = "2021"

[dependencies]
fleet_app = { workspace = true }

eframe = { workspace = true }
egui = { workspace = true }
rfd = "0.15"
serde_json = { workspace = true }
velopack = { workspace = true }

tokio = { workspace = true }
parking_lot = { workspace = true }
