[package]
name = "fleet-cli"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[dependencies]
fleet-core = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
indicatif = "0.17.11"
tracing = { workspace = true }

[dev-dependencies]
fleet-domain = { workspace = true }
serde_json = { workspace = true }
swifty_artifacts = { workspace = true }

[[bin]]
name = "fleet-cli"
path = "src/main.rs"
