[package]
name = "fleet-cli"
version = "4.0.0-beta.2"
edition = "2021"
build = "build.rs"

[dependencies]
fleet-core = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
indicatif = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
fleet-domain = { workspace = true }
serde_json = { workspace = true }
swifty_artifacts = { workspace = true }
tempfile = { workspace = true }

[[bin]]
name = "fleet-cli"
path = "src/main.rs"
