[package]
name = "coordinator"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1"
futures-util = "0.3"
manifest_types = { path = "../manifest_types" }
remote_core = { path = "../remote_core" }
remote_http = { path = "../remote_http" }
relative-path = "1.9"
sync_apply = { path = "../sync_apply" }
sync_plan = { path = "../sync_plan" }
thiserror = "2"
tokio = { version = "1.43", features = ["macros", "rt-multi-thread", "sync"] }
walkdir = "2"

[dev-dependencies]
serde_json = "1.0"
tempfile = "3"
wiremock = "0.6"
local_index = { path = "../local_index" }
md-5 = "0.10"
axum = "0.7"
tower-http = { version = "0.5", features = ["fs"] }
