[package]
name = "remote_adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
bytes = "1"
futures = "0.3"
md-5 = "0.10"
relative-path = "1.9"
remote_core = { path = "../remote_core" }
remote_http = { path = "../remote_http" }
manifest_types = { path = "../manifest_types" }
sync_engine = { path = "../sync_engine" }
tokio = { version = "1", features = ["sync"] }

[dev-dependencies]
tempfile = "3"
