[package]
name = "fleet-domain"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
fleet-local-state = { workspace = true }
serde = { workspace = true }
specta = { workspace = true }
url = { workspace = true }
sha1 = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tempfile = { workspace = true }
