[package]
name = "fleet-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
fleet-download = { workspace = true }
fleet-domain = { workspace = true }
fleet-inventory = { workspace = true }
fleet-flux = { workspace = true }
flux = { workspace = true }
prodash = { workspace = true }
swifty-repo = { workspace = true }
swifty_artifacts = { workspace = true }
directories = { workspace = true }
fleet-arma3 = { workspace = true }
shell-words = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
specta = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tempfile = { workspace = true }
atomic-write-file = { workspace = true }
fs2 = { workspace = true }
ignore = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }
futures-util = { workspace = true }
sentry = { workspace = true, features = ["logs", "tracing"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
regex = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
