[package]
name = "fleet-manifest"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
fleet-download = { workspace = true }
flux-manifest = { workspace = true }
flux-types = { workspace = true }
swifty-repo = { workspace = true }
swifty_artifacts = { workspace = true }
url = { workspace = true }
