[package]
name = "fleet"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
camino = { workspace = true }
fleet_app = { workspace = true }
fleet-ui = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
velopack = { workspace = true }

[dev-dependencies]
assert_cmd = "2"
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
sha2 = "0.10"
tempfile = "3"
urlencoding = "2"
walkdir = "2"
serde = { workspace = true }
