[package]
name = "fleet"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "time"] }
dotenvy = "0.15.7"
open = "5.3.3"
rfd = "0.17.2"
directories = { workspace = true }
icondata = { version = "0.7.0", default-features = false, features = ["bootstrap-icons", "font-awesome", "ionicons", "remix-icon", "weather-icons"] }

fleet-core = { workspace = true }
fleet-domain = { workspace = true }
swifty-repo = { workspace = true }
velopack = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
chrono = { workspace = true }
semver = "1.0.27"
base64 = "0.22.1"
image = { version = "0.25.6", default-features = false, features = ["png"] }

# Dioxus
dioxus = { version = "0.7.3", features = ["desktop", "router"] }
dioxus-logger = "0.7.3"
tracing = { workspace = true }
dioxus-router = "0.7.3"

[build-dependencies]

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1.20"
