[package]
name = "fleet-download"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
atomic-write-file = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
reqwest-retry = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
